### PR TITLE
SPDX conjunction / disjunction operators are capitalized

### PR DESCRIPTION
**Pull request by FelixZhang**
See https://spdx.org/spdx-specification-21-web-version

Fixes: #21

### CODE REVIEW

**Comment by coolo** [comment]
but this break all existant and/or - and we have quite some of them. And due to the lack of test cases in this module, I would rather not merge this.

**Comment by FelixZhang** [comment]
Understood. Thanks very much for the comment. I could keep the back compatibility for the lower cases. By the way, do you think it make sense to let this script warn the maintainers to capitalize those words?

**Comment by coolo** [comment]
I guess the next to complain will be rpmlint. But having it correct SPDX would be good - so transforming is ok

**Comment by mimi1vx** [comment]
@coolo openSUSE rpmlint is patched to accept `and|or|AND|OR`

**Comment by coolo** [comment]
on all platforms?

**Comment by mimi1vx** [comment]
openSUSE:Tumbleweed

**Comment by scarabeusiv** [comment]
I backported the check fix for rpmlint in all maintained products, now it is in maintenance queue.

**Pull request merged**
