### PR TITLE
Use URL instead of Url

### PR DESCRIPTION
**Pull request by DimStar77**
There are currently two tools performing similar actions, spec-cleaner and
format_spec_file. And at this moment they fight over who is right how to
format URL.

### CODE REVIEW

**Comment by DimStar77** [comment]
to match up with https://github.com/openSUSE/spec-cleaner/commit/a82a7330980afa8488d40c0827d7820762942ce7

**Comment by coolo** [comment]
this will be *very* noisy

**Comment by DimStar77** [comment]
the problem is currently we have a lot of packages switching between Url and URL, depending on if the user is using spec-cleaner for format_spec_file as his service of choice. The two really have to use the same here

**Comment by dirkmueller** [comment]
Would it be possible to accept both and not change it? This has a chance for desaster otherwise. We do have one or two distros other than tumbleweed as well inour portfolio.

(Tbh I still don't get why we were switching from URL to Url)

**Comment by DimStar77** [comment]
My other option is to revert this in spec-cleaner; I don't mind either way.. this half-switched thing is just nonsense.

**Comment by coolo** [comment]
I opt for doing what Dirk said: don't change at all in prepare_spec. Have those prefering URL their way, but leave the rest

**Comment by DimStar77** [comment]
ok, updated the PR... If URL is either Url or URL, we just leave it in place, if it's any other spelling form, we normalize to 'Url' now.

**Pull request merged**
